apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qslate

resources:
  - ../../base/runner-api
  - ../../base/backend-api
  - ../../base/frontend

patches:
  - path: runner-api/patch-image.yaml
    target:
      kind: Deployment
      name: runner
  - path: backend-api/patch-image.yaml
    target:
      kind: Deployment
      name: backend
  - path: frontend/patch-image.yaml
    target:
      kind: Deployment
      name: frontend
