apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: runner
          image: ghcr.io/qslate/runner:latest
          imagePullPolicy: Always